os: Visual Studio 2017

platform:
  - x64

environement:
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc

cache:
  - gameserver\target
  - planetwars\client\node_modules
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\.cargo'

init:
  - git config --global core.autocrlf input

# Download rust
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - ps: Install-Product node 9 x64

build_script:
 - cd gameserver
 - cargo build --release