env:
  gobal: 
     - ELECTRON_CACHE=$HOME/.cache/electron
     - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

matrix:
  include:
  - os: linux
    language: rust
    rust: nightly
    node_js: '9'
    env: 
     - OS_TARGET="linux"
  - os: osx
    osx_image: xcode9.2
    language: rust
    node_js: '9'
    rust: nightly
    env:
      - OS_TARGET="mac"


cache:
  directories:
    - gameserver/target/
    - client/planetwars/node_modules
    - $HOME/.cargo/
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi
before_script:
  - git lfs pull

script:
  - cd gameserver
  - cargo build --release
  - cd $TRAVIS_BUILD_DIR
  - mv gameserver/target/release/mozaic_bot_driver planetwars/client/bin/mozaic_bot_driver
  - cd planetwars/client
  - npm install
  - npm run package-$OS_TARGET