[package]
name = "mozaic"
version = "0.0.0"
authors = ["Zeus WPI", "Weledelgeboren heer ridder Olivier Dimitri Lea Guillain Marie de Schaetzen"]

[dependencies]
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0"
