[package]
name = "codegen"
version = "0.1.0"
authors = ["Ilion Beyst <ilion.beyst@gmail.com>"]

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"


[[bin]]
name = "testbin"
path = "src/main.rs"